### ISSUE TITLE
capability to convert timestamp to hour, day of week

### ISSUE THREAD

**Issue by aarshayj** [spotify/featran#114]
if i'm correct, , featran does not have capability to convert timestamp to hour, time and maybe even a different time zone.

how much effort (#hours?) would be required to add this capability? happy to contribute PR if its feasible in my time constraints..

**Comment by nevillelyh** [comment]
It's trivia but probably outside the scope of featran.
You can just do it in the extraction function i.e. `FeatureSpec#required(f)` or `FeatureSpec#optional(f)` without even implementing a transformer.

**Comment by aarshayj** [comment]
i'm new to featran.. it'll be great if we can do it without a new transformer..
is there an example you have off-the-bat which I can refer?

**Comment by nevillelyh** [comment]
```scala
FeatureSpec.of[MyRecord]
  .required(r => someFunction(r.getSomeField))(Identity("x"))
```

Basically the README, which has links to the examples.

**Comment by aarshayj** [comment]
thanks!
