### ISSUE TITLE
featran does not normalize feature names

### ISSUE THREAD

**Issue by yonromai** [spotify/featran#119]
This can be a problem when using scio's [TFRecordSpec](https://github.com/spotify/scio/blob/master/scio-tensorflow/src/main/scala/com/spotify/scio/tensorflow/TFRecordSpec.scala), where TF doesn't like things like space in the feature name.

**Comment by nevillelyh** [comment]
Discussed IRL. Since this is TensorFlow specific, I think it make sense to have normalization built into `FeatureBuilder[Example]`?

**Comment by ravwojdyla** [comment]
still failing in 0.1.27: `ValueError: 'track.gracenote_era_0_Early 20th C.' is not a valid scope name`

**Comment by ravwojdyla** [comment]
actually it might be a red herring - double checking.

**Comment by ravwojdyla** [comment]
Actually it's fine - it's a bug in scio.
