### ISSUE TITLE
Can we use scaladoc 2.12?

### ISSUE THREAD

**Issue by regadas** [spotify/featran#134]
It would be great if we could use it because scaladoc 2.12 is much nicer! 😄

**Comment by nevillelyh** [comment]
Not sure how to go about it. We're stuck with 2.11 since Spark, Fink & XGBoost do not support 2.12 yet. 
Don't think sbt-unidoc can mix 2.11 & 2.12 style docs. We might have to exclude `featran-{java,spark,flink,xgboost}` from sbt-unidoc.

**Comment by nevillelyh** [comment]
We cross build everything for 2.12 now as of 0.4.0 and scaladoc is 2.12.
