### ISSUE TITLE
PositionEncoder doesn't support input as "Seq" of Strings

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/featran#142]
Right now `PositionEncoder` extends `BaseHotEncoder[String]` which forces the input to be `String`, we should also allow input as `Seq[String]`.

**Comment by nevillelyh** [comment]
What would the output dimension be in this case?
For input of a single `String`, output is always 1 dimension of position of that string within the observed categories.
For input of `Seq[String]` with varying sizes, should output dimension be `N` the total vocabulary size like `OneHotEncoder`?

**Comment by ravwojdyla** [comment]
@nevillelyh best case would be to get variable size length vector containing indices, but I can see how that would not work in Featran. If we go for `N` (the total vocabulary size), we might as well use `NHotEncoder`.

**Comment by nevillelyh** [comment]
Doesn't look like there's a good solution. Should we close this then?
