### ISSUE TITLE
Upgrade TensorFlow to 1.9.0

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/featran#170]
https://github.com/tensorflow/tensorflow/releases/tag/v1.9.0

**Comment by nevillelyh** [comment]
Looks like the `1.9.0` artifacts are not out yet. The latest available are `1.9.0-rc2`.
https://mvnrepository.com/artifact/org.tensorflow/tensorflow

**Comment by ravwojdyla** [comment]
will probably come out in a couple of days, as per looking at dates in https://repo.maven.apache.org/maven2/org/tensorflow/tensorflow/

**Comment by regadas** [comment]
Closed via #171
