### ISSUE TITLE
one hot encoder for large N

### ISSUE THREAD

**Issue by slhansen** [spotify/featran#20]
The one hot encoder takes a long time to run when the number of tokens is large. I believe the problem lies in the fact that the current implementation iterates over each element in the dictionary:

https://github.com/spotify/featran/blob/master/core/src/main/scala/com/spotify/featran/transformers/OneHotEncoder.scala#L45

I tried writing an implementation that uses a hash map instead of a list to store the tokens (plus their index), but it is still necessary to "inflate" the feature with the empty elements.

https://github.com/slhansen/featran/blob/master/core/src/main/scala/com/spotify/featran/transformers/OneHotEncoder.scala#L57-#L68

Since we can assume that only one element will be added it would be preferable to have the default be an empty feature vector and just add one element to it given the index.

**Comment by slhansen** [comment]
@nevillelyh ^

**Comment by richwhitjr** [comment]
Makes sense, in the skip function you can already specify N.  So we could be smarter about overriding this in the implementation functions as to not loop over the empty elements. 

So we could find the index into the one hot encoding list, skip up that, fill in the zero, then skip to the end.

**Comment by slhansen** [comment]
@richwhitjr I tried the approach of making use of the the skip function n-1 times (see second link in original comment) but it is still slow. My use case is for encoding user IDs so n is ~10^7.

**Comment by richwhitjr** [comment]
I think the issue here is that the subclasses don't implement skip(n) in an efficient way.  It may make sense to implement it in each subclass as needed for performance.  Right now with the default implementation I believe it is doing O(n) still even with the skipping.

https://github.com/spotify/featran/blob/master/core/src/main/scala/com/spotify/featran/FeatureBuilder.scala#L43

**Comment by nevillelyh** [comment]
Does either of you wanna submit a PR? Otherwise we can look into it.
