### ISSUE TITLE
Add transformers to handle outliers and unbalanced data

### ISSUE THREAD

**Issue by nevillelyh** [spotify/featran#32]
- maybe quantiles for outliers
- SMOTE: Synthetic Minority Over-Sampling Technique for unbalanced

**Comment by richwhitjr** [comment]
Unbalanced data meaning unbalanced labels?  Should Featran care about labels and balancing?  I feel like that would be either an extension to the use case for the current library or a new library all together. 

I guess the big change to do label balancing from a concept standpoint is that you still have the aggregation but now the final map function requires a flatMap where you can output a row 0 to N times.  Also a lot of ways you can deal with balancing that depend on the use case and amount of data you have available.

**Comment by nevillelyh** [comment]
Fixed in #66
