### ISSUE TITLE
Allow transformer to reject inputs

### ISSUE THREAD

**Issue by nevillelyh** [spotify/featran#33]
By adding a method to `FeatureBuilder`, so any `Transformer` in the spec can call it to reject an entire record.

**Comment by richwhitjr** [comment]
Reject meaning zero out or don't output the vector entirely?  This for cases like outliers or one hot encoded enums where the aggregator doesn't have an entry?

**Comment by nevillelyh** [comment]
Not zero, but some separate output indicating some error, e.g. out of bound, outlier. Users can choose to keep the output (likely zeroed out) or filter the entire records out if error exists.
We can represent `FeatureBuilder` output something like a `Try[T]` or cats `Validation`.

**Comment by richwhitjr** [comment]
I see, makes sense.  Exposing errors and allowing people to decide what to do with them is always a good path. If nothing else there will be cases where the function that is passed to the transformer will hit malformed data.
