### ISSUE TITLE
Frequency rank transformer

### ISSUE THREAD

**Issue by nevillelyh** [spotify/featran#48]
Feature request from an internal user:
"I want to transform a string feature to integer ids, where the most common string gets id 1, second most common gets id 2, etc. and have a cap at at 10000, so everything else gets mapped to 0. Is that easily doable with featran?
The original dataset might have say 1 billion strings (of which say 1 million are unique)."

Not sure if this can be done with approximation in a single pass. The naive approach would be building a `Map[String, Int]` in `reduce` phase and a priority queue before `map` phase.

**Comment by richwhitjr** [comment]
We can maybe also use a SketchMap in Algebird set to 10,000 and use the heavy hiters to add ordinal features on the frequency.

**Comment by nevillelyh** [comment]
Great! Played around `SketchMap` a bit and we can achieve the desired rank with the following snippet:

```scala
import com.twitter.algebird._

// scalastyle:off
object Test {
  def main(args: Array[String]): Unit = {
    def freq(x: Int) =
      if(x < 10) 1
      else if (x < 100) 2
      else if (x < 200) 4
      else if (x < 300) 8
      else if (x < 400) 16
      else if (x < 500) 32
      else if (x < 600) 64
      else if (x < 700) 128
      else if (x < 800) 256
      else x
    val data = (1 to 1000).toParArray
      .map(x => ("key%05d".format(x), freq(x)))
      .flatMap(kv => (1 to kv._2).map(_ => (kv._1, 1)))

    val params = SketchMapParams[String](1, 0.01, 1e-3, 100)(_.getBytes)
    val aggregator = SketchMap.aggregator[String, Int](params)
    val m = data
      .map(aggregator.prepare)
      .reduce(aggregator.monoid.plus)
    println(m.totalValue)
    println(m.heavyHitterKeys.size)
    println(m.heavyHitterKeys.sorted)

    m.heavyHitterKeys.foreach(k => println(k, params.frequency(k, m.valuesTable)))
  }
}
```

**Comment by nevillelyh** [comment]
So we can probably generate 2 output columns, 1 rank and 1 estimate count.
For rank does `[1, n]` (where `1` is most frequent and `n` is nth, and rest is `0`) make sense? Or should it be `[0, n-1]` and `Int.MaxValue` for rest?

**Comment by richwhitjr** [comment]
Not sure, 0 or empty sounds correct.  May be worth asking the user who wanted the feature.

**Comment by maris382** [comment]
[I'm the internal user] 
0 is more useful if you want to use it for tensorflow embedding lookups (tf.nn.embedding_lookup)
