### ISSUE TITLE
Add ngrams transformer

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/featran#52]
See https://github.com/tensorflow/transform/blob/master/tensorflow_transform/mappers.py#L399

**Comment by nevillelyh** [comment]
This can be treated as an `n`-hot to `m` transformer, i.e. `Seq[String]` to `Seq[String]` where `m` is n-gram combinations of `n` input words. But the total vocabulary space might explode. Not sure if worth it.

**Comment by richwhitjr** [comment]
Probably one of things to add if people ask for this.  I have used something similar to this in the past but just created the n grams prior to the n-hot encoder instead of in the transformer.
