### ISSUE TITLE
Remove QTreeSerializer workaround

### ISSUE THREAD

**Issue by nevillelyh** [spotify/featran#98]
Once upstream is merged.
https://github.com/twitter/chill/pull/305

**Comment by ClaireMcGinty** [comment]
@nevillelyh it looks like Featran is currently pulling in Chill transitively from its Scio dependency, once Scio 0.5.7 is released we can just update `scioVersion` and pull in Chill 0.9.3 automatically?

**Comment by nevillelyh** [comment]
Sounds good. And then we can remove this https://github.com/spotify/featran/blob/master/scio/src/main/scala/com/spotify/featran/scio/FeatranKryoRegistrar.scala
